function apply_plot_style(fig, cfg)
%APPLY_PLOT_STYLE Apply shared plotting style to a project figure.

if nargin < 1 || isempty(fig)
    fig = gcf;
end
if nargin < 2 || isempty(cfg)
    cfg = struct();
end

fontName = plot_style_value(cfg, 'plotFontName', 'Helvetica');
fontSize = plot_style_value(cfg, 'plotFontSize', 13);
titleFontSize = plot_style_value(cfg, 'plotTitleFontSize', fontSize + 1);
titleFontWeight = plot_style_value(cfg, 'plotTitleFontWeight', 'normal');
axesFontWeight = plot_style_value(cfg, 'plotAxesFontWeight', 'normal');
axesLineWidth = plot_style_value(cfg, 'plotAxesLineWidth', 1.0);
lineWidth = plot_style_value(cfg, 'plotLineWidth', 1.5);
textColor = plot_style_value(cfg, 'plotTextColor', 'black');
interpreter = plot_style_value(cfg, 'plotTextInterpreter', 'tex');
legendInterpreter = plot_style_value(cfg, 'plotLegendInterpreter', interpreter);
tickLabelInterpreter = plot_style_value(cfg, 'plotTickLabelInterpreter', interpreter);

set(fig, ...
    'DefaultTextFontName', fontName, ...
    'DefaultAxesFontName', fontName, ...
    'DefaultTextFontSize', fontSize, ...
    'DefaultAxesFontSize', fontSize, ...
    'DefaultTextFontWeight', axesFontWeight, ...
    'DefaultAxesFontWeight', axesFontWeight, ...
    'DefaultAxesLineWidth', axesLineWidth, ...
    'DefaultLineLineWidth', lineWidth, ...
    'DefaultTextColor', textColor, ...
    'DefaultTextInterpreter', interpreter, ...
    'DefaultAxesTickLabelInterpreter', tickLabelInterpreter, ...
    'DefaultLegendInterpreter', legendInterpreter);

set(findall(fig, '-property', 'FontName'), 'FontName', fontName);
set(findall(fig, '-property', 'FontSize'), 'FontSize', fontSize);
set(findall(fig, '-property', 'Interpreter'), 'Interpreter', interpreter);
set(findall(fig, '-property', 'TickLabelInterpreter'), ...
    'TickLabelInterpreter', tickLabelInterpreter);

axesHandles = findall(fig, 'Type', 'axes');
for ax = reshape(axesHandles, 1, [])
    set(ax, ...
        'FontName', fontName, ...
        'FontSize', fontSize, ...
        'FontWeight', axesFontWeight, ...
        'LineWidth', axesLineWidth, ...
        'TickLabelInterpreter', tickLabelInterpreter);

    set(ax.Title, ...
        'FontName', fontName, ...
        'FontSize', titleFontSize, ...
        'FontWeight', titleFontWeight, ...
        'Color', textColor, ...
        'Interpreter', interpreter);

    set(ax.XLabel, ...
        'FontName', fontName, ...
        'FontSize', fontSize, ...
        'FontWeight', axesFontWeight, ...
        'Color', textColor, ...
        'Interpreter', interpreter);

    set(ax.YLabel, ...
        'FontName', fontName, ...
        'FontSize', fontSize, ...
        'FontWeight', axesFontWeight, ...
        'Color', textColor, ...
        'Interpreter', interpreter);

    set(ax.ZLabel, ...
        'FontName', fontName, ...
        'FontSize', fontSize, ...
        'FontWeight', axesFontWeight, ...
        'Color', textColor, ...
        'Interpreter', interpreter);
end

textHandles = findall(fig, 'Type', 'text');
for textHandle = reshape(textHandles, 1, [])
    set(textHandle, ...
        'FontName', fontName, ...
        'FontSize', fontSize, ...
        'FontWeight', axesFontWeight, ...
        'Color', textColor, ...
        'Interpreter', interpreter);

    tag = get(textHandle, 'Tag');
    if contains(lower(tag), 'title')
        set(textHandle, ...
            'FontName', fontName, ...
            'FontSize', titleFontSize, ...
            'FontWeight', titleFontWeight, ...
            'Color', textColor, ...
            'Interpreter', interpreter);
    end
end

lineHandles = findall(fig, 'Type', 'line');
for lineHandle = reshape(lineHandles, 1, [])
    if get(lineHandle, 'LineWidth') <= 0.5
        set(lineHandle, 'LineWidth', lineWidth);
    end
end

legendHandles = findall(fig, 'Type', 'legend');
for legendHandle = reshape(legendHandles, 1, [])
    set(legendHandle, ...
        'FontName', fontName, ...
        'FontSize', fontSize, ...
        'TextColor', textColor, ...
        'Interpreter', legendInterpreter);
end

colorbarHandles = findall(fig, 'Type', 'colorbar');
for colorbarHandle = reshape(colorbarHandles, 1, [])
    set(colorbarHandle, ...
        'FontName', fontName, ...
        'FontSize', fontSize, ...
        'FontWeight', axesFontWeight, ...
        'LineWidth', axesLineWidth, ...
        'TickLabelInterpreter', tickLabelInterpreter);

    set(colorbarHandle.Label, ...
        'FontName', fontName, ...
        'FontSize', fontSize, ...
        'FontWeight', axesFontWeight, ...
        'Color', textColor, ...
        'Interpreter', interpreter);
end

end

function value = plot_style_value(cfg, fieldName, defaultValue)

if isfield(cfg, fieldName)
    value = cfg.(fieldName);
else
    value = defaultValue;
end

end
